import type { MetadataRoute } from 'next'
import storiesData from '@/data/success-stories.json'

const baseUrl = 'https://mitigence.com'

const staticRoutes = [
  '/',
  '/about',
  '/approach',
  '/careers',
  '/company',
  '/consultation',
  '/contact',
  '/privacy',
  '/terms',
  '/engineering',
  '/engineering/architecture',
  '/engineering/configuration-review',
  '/engineering/deployment',
  '/engineering/health-checks',
  '/engineering/integration',
  '/engineering/operational-readiness',
  '/engineering/optimization',
  '/industries',
  '/industries/education',
  '/industries/financial-services',
  '/industries/government',
  '/industries/healthcare',
  '/industries/manufacturing',
  '/industries/retail',
  '/knowledge',
  '/knowledge/applications',
  '/knowledge/architecture',
  '/knowledge/cloud',
  '/knowledge/data',
  '/knowledge/identity',
  '/knowledge/incident-response',
  '/knowledge/monitoring',
  '/knowledge/network',
  '/leadership',
  '/platform',
  '/platform/engineer',
  '/platform/engineer/capability-explorer',
  '/platform/engineer/delivery-framework',
  '/platform/engineer/delivery-models',
  '/platform/engineer/engagement-studio',
  '/platform/engineer/engineering-studio',
  '/platform/engineer/team-builder',
  '/platform/operate',
  '/platform/operate/continuous-improvement',
  '/platform/operate/customer-success',
  '/platform/operate/customer-workspace',
  '/platform/operate/project-timeline',
  '/platform/operate/reports',
  '/platform/understand',
  '/platform/understand/enterprise-explorer',
  '/platform/understand/industry-challenges',
  '/platform/understand/knowledge-center',
  '/platform/understand/security-journey',
  '/platform/understand/threat-insights',
  '/solutions',
  '/solutions/applications',
  '/solutions/cloud',
  '/solutions/data',
  '/solutions/endpoints',
  '/solutions/identity',
  '/solutions/monitoring',
  '/solutions/network',
  '/solutions/remote-access',
  '/success-stories',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const storyRoutes = storiesData.stories.map((s) => `/success-stories/${s.slug}`)
  return [...staticRoutes, ...storyRoutes].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '/' ? 'weekly' : 'monthly',
    priority: route === '/' ? 1 : route.split('/').length <= 2 ? 0.8 : 0.6,
  }))
}
